SystemOrganization addCategory: #'Apache-Solar-Core'!
SystemOrganization addCategory: 'Apache-Solar-Core-Exceptions'!
SystemOrganization addCategory: 'Apache-Solar-Core-Facet'!
SystemOrganization addCategory: 'Apache-Solar-Core-Fields'!
SystemOrganization addCategory: 'Apache-Solar-Core-Highlighting'!
SystemOrganization addCategory: 'Apache-Solar-Core-Others'!
SystemOrganization addCategory: 'Apache-Solar-Core-SpecialTypes'!
